name: Auto Close Issue

on:
  pull_request:
    types: [closed]

jobs:
  auto-close-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'develop'
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const issueNumber = getIssueNumberFromBranchName(branchName);
            if (issueNumber) {
              github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: 'closed'
              });
            }

            function getIssueNumberFromBranchName(branchName) {
              const match = branchName.match(/feature\/#(\d+)-.*/);
              return match ? parseInt(match[1], 10) : null;
            }
    permissions:
        issues: write