name: black and ruff

on:
  pull_request:
    branches:
      - 'develop'
      - 'release'
      - 'main'

jobs:
  Black_code_formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "-l 79 --diff --color --check"
          src: "./"
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: "--ignore F403"
          src: "./"